### ISSUE TITLE
Zoom and Lecture Recordings

### ISSUE THREAD

**Issue by mikeizbicki** [mikeizbicki/cmc-csci181-languages#1]
All lectures will be broadcast live on zoom at the following url: https://cmc-its.zoom.us/j/3952597181.

**Comment by mikeizbicki** [comment]
I've just uploaded the first class lecture to the youtube playlist <https://www.youtube.com/playlist?list=PLSNWQVdrBwoa4KNaiKr-ayUdROZdSZ_1E>.  All future lectures will be uploaded there as well.

**Comment by maxplush** [comment]
Just flagging that the first class lecture that was uploaded doesn't have any audio.

**Comment by mikeizbicki** [comment]
@maxplush Whoops!  Looks like I forgot to turn on the audio on zoom... I'll try to be better about that in the future.

**Comment by mikeizbicki** [comment]
I've just uploaded the class lecture video, and it has sound this time :)

In the future, I won't post individual updates after each video is uploaded, but expect them to be uploaded shortly after class.

**Comment by danzhechen** [comment]
Hi Mike, could you upload today's recording to youtube? Thank you so much!

**Comment by mikeizbicki** [comment]
@danzhechen It should be uploaded now at <https://www.youtube.com/watch?v=6ie5ouWixk8>.  Sorry for the delay.

**Comment by EthanTu2** [comment]
Hi Mike, can you upload the recording for Wednesdays lecture to Youtube please? Thanks!

**Comment by EthanTu2** [comment]
> Hi Mike, can you upload the recording for Wednesdays lecture to Youtube please? Thanks!

Nevermind, I have heard that there wasn't a recording for that class.
