### ISSUE TITLE
Downloading metahtml 

### ISSUE THREAD

**Issue by luisgomez214** [mikeizbicki/cmc-csci181-languages#15]
Hello, 

I followed the instructions of the meta HTML repo to download it and this is what I am getting on the terminal. 

```
(venv) luis@Luiss-MacBook-Pro-40 ragnews1 % cd metahtml 
(venv) luis@Luiss-MacBook-Pro-40 metahtml % ls
MANIFEST.in		conftest.py		requirements.txt
README.md		hostnames.csv		setup.py
``` 

Is this correct? I am missing files that are on the repo, but the instructions did say all unnecessary files wont be cloned.

**Comment by finnless** [comment]
No, its missing the metahtml module. Refer to this PR for a fix: https://github.com/mikeizbicki/metahtml/pull/206.
