### ISSUE TITLE
AttributeError: module 'ragnews' has no attribute 'ArticleDB'

### ISSUE THREAD

**Issue by danzhechen** [mikeizbicki/cmc-csci181-languages#20]
Hi there, 

I encountered this problem but I do not really know how to fix that. I just built up my evaluate.py which is under ragnews folder. Same code as Mike did in class. 

```
'''
This file is for evaluating the quality of our RAG system using the Hairy Trumpet tool/dataset.
'''

import sys 
sys.path.append('..')
import ragnews

class RAGEvaluator:
    def predict(self, x): 
        ''' 
        >>> model = RAGEvaluator()
        >>> model.predict('There no mask token here.')
        []
        >>> model.predict('[MASK0] is the democratic nominee')
        'Harris'
        >>> model.predict('[MASK0] is the democratic nominee and [MASK1] is the republican nominee')
        ['Harris', 'Trump']
        '''
        # you might think about:
        # calling the ragnews.run llm function directly;
        # so we will call the ragnews.rag function
    
        db = ragnews.ArticleDB()
        textprompt = 'hello world'
        ragnews.rag(textprompt, db) 
```
However, I encountered this problem. 
```
AttributeError: module 'ragnews' has no attribute 'ArticleDB'
```
I am a bit confused. Because I first got this error by running this command, 
```
Dan-Macbook:~/proj/ragnews (evaluation *+%) $ python3 -i ragnews/evaluate.py
Traceback (most recent call last):
  File "/Users/JerryChen/proj/ragnews/ragnews/evaluate.py", line 5, in <module>
    import ragnews
ModuleNotFoundError: No module named 'ragnews'
```
I fixed that by adding this at the beginning of my code, 
```
import sys
sys.path.append('..')
```
Why do I still have the issue described in the title? Any help would be appreciated!

**Comment by mikeizbicki** [comment]
The python import system is complicated enough that I'm not going to be able to help out with this over github issues because there are too many system-dependent configuration things that could potentially be causing the problem :(

I can say, however, that these lines
```
import sys
sys.path.append('..')
```
are definitely wrong and not something you should ever do.

Also, #18 covers the "right" way to get `ragnews` to import if you haven't seen it.

**Comment by danzhechen** [comment]
I think #18 helps me solve the problem. But two questions, one why is that command I used bad? Second why is this command working? 
```
export PYTHONPATH=.
```
