### ISSUE TITLE
Class 10/16 recording

### ISSUE THREAD

**Issue by aopsahl25** [mikeizbicki/cmc-csci181-languages#27]
Professor Izbicki - would you posting the recording from yesterday's class? Thank you so much!

**Comment by mikeizbicki** [comment]
It's uploaded at <https://www.youtube.com/watch?v=uwbRzH9Z-ug>.  For some reason, youtube put it at the bottom of the playlist rather than the top ¯\\_(ツ)_/¯

**Comment by aopsahl25** [comment]
Ohh I see. Thank you and sorry for missing that!
