### ISSUE TITLE
AO Project rubric

### ISSUE THREAD

**Issue by aopsahl25** [mikeizbicki/cmc-csci181-languages#31]
[Final project grading rubric.pdf](https://github.com/user-attachments/files/17594047/Final.project.grading.rubric.pdf)

**Comment by mikeizbicki** [comment]
I suggest clarifying the following points:

1. For T4 and T5, it's not obvious to me how LMQL can be used to help with function output or chatbots.  Chat, for example, tends to have little structure; but LMQL is about enforcing structure, so what structure will you be enforcing in the chatbot's output?
2. The evaluation component is still a bit ambiguous.  For example, you mention "measuring the accuracy of the sentiment classification", but is there a specific dataset you will be using?
3. For social media: 
    1. I suggest also contacting the LMQL authors.  Possibly as a pull request into the README file with a link to your tutorial, or possibly as an email.
    2. Your LMQL tutorial will probably be relying on OpenAI as a backend instead of a local model.  (LMQL supports a llama.cpp backend which you could use, but you'd need to have a beefy enough computer to do so.)  That's going to make it less appealing to the /r/LocalLlama crowd, and more appealing to other groups.  So I recommend finding a few other subreddits/social media sites to target.

**Comment by aopsahl25** [comment]
Attached is a new pdf rubric with updates based on your feedback. Please let me know if you have any further suggestions. Thanks! 
[Final project grading rubric (1).pdf](https://github.com/user-attachments/files/17641771/Final.project.grading.rubric.1.pdf)

**Comment by mikeizbicki** [comment]
The changes all look good :)
