### ISSUE TITLE
Arithmetic Homework Question

### ISSUE THREAD

**Issue by danzhechen** [mikeizbicki/cmc-csci181-languages#33]
Hi there, 

I am working on the arithmetic homework and specifically the interpreter class right now. The issue I am dealing is that the visit function for the tree will return a nested list. And I think both methods work but I just wonder whether there exists a better approach among the two. The first is simple and easy but I am not sure whether overwrite would be a problem. The second method is very lengthy. 

1. Overwrite the visit
I use something like this to overwrite the visit function. 
```
def visit(self, tree):
        result = super().visit(tree)
        return result if not isinstance(result, list) else result[0]
```
2. Define the function for all the intermediate nodes
Like define the atom as a function
```
def atom(self, tree):
        return self.visit(tree.children[0])
```

**Comment by mikeizbicki** [comment]
Overwriting `visit` is not correct.  You're supposed to define a method for each of the nodes.  This shouldn't be significantly more lengthy than for the `Simplifier` class.
