### ISSUE TITLE
Final Project Grading Rubric - Dan

### ISSUE THREAD

**Issue by danzhechen** [mikeizbicki/cmc-csci181-languages#34]
![image](https://github.com/user-attachments/assets/885ea5c6-b4cd-4ead-bdcf-dab4188300d5)
[Final Project Grading Rubric.pdf](https://github.com/user-attachments/files/17639686/Final.Project.Grading.Rubric.pdf)

**Comment by mikeizbicki** [comment]
I don't think the files uploaded correctly.  When I click the attached link, it goes to Amelia's project instead of yours.

**Comment by danzhechen** [comment]
> I don't think the files uploaded correctly. When I click the attached link, it goes to Amelia's project instead of yours.

Just modified!

**Comment by danzhechen** [comment]
Updated new rubric:
[Final project grading rubric DC.pdf](https://github.com/user-attachments/files/17689611/Final.project.grading.rubric.DC.pdf)

**Comment by mikeizbicki** [comment]
Big picture idea of everything is good.

Minor points:

1. There's still some details in here that I think you will find very challenging to overcome.  I like your ambition, so I will lean on the generous side when grading this.  
2. Pagila is not what I'd consider a "large dataset".  For working on actually large datasets, you'd need to also be writing indexes, which is not part of your current rubric (and realistically probably shouldn't be for time constraint reasons).
