### ISSUE TITLE
Final Project Rubric

### ISSUE THREAD

**Issue by abizermamnoon** [mikeizbicki/cmc-csci181-languages#36]
[Grading Rubric - Sheet1.pdf](https://github.com/user-attachments/files/17616085/Grading.Rubric.-.Sheet1.pdf)

**Comment by mikeizbicki** [comment]
You need to:

1. Provide much more detail.  
2. Describe how you will evaluate your system experimentally.
3. Readjust the weights.  Currently 75% of your grading weight is on scraping data and sticking it into the database.  That's all intro CS stuff and not stuff related to this course.  I would expect this portion of the project to weigh at most 30%.

**Comment by abizermamnoon** [comment]
<img width="659" alt="image" src="https://github.com/user-attachments/assets/6dec9069-0b76-4ee0-b919-9b185f515832">

**Comment by mikeizbicki** [comment]
Your totals only add up to 90%.

The ideas behind your queries in the experimental portion look good, but you should also specify some concrete number of examples you will test that follow that format.

**Comment by abizermamnoon** [comment]
Hi Mike,
I made the changes you suggested. Can you have another look:

<img width="620" alt="image" src="https://github.com/user-attachments/assets/b57dd63c-921f-4d52-b02e-3c37c7fd5db5">
