### ISSUE TITLE
Poll Classifier Project Rubric

### ISSUE THREAD

**Issue by finnless** [mikeizbicki/cmc-csci181-languages#37]
**Title:** Build open-text social survey response coder library
**Team:** Nolan
**Project Description:** This project is an open-source library that uses language models to code open-ended survey responses. It is designed to be accessible to social science researchers. Features include setting a codebook, inputting survey responses, and validating classifier accuracy with labeled test data.

**Rubric:**

| **Percent of Grade** | **Task Description** |
|----------------------|----------------------|
| **15%** | **Project Setup**<br> - Create a `README.md` with instructions for setting up the environment, installing dependencies, and running the model. The setup must be clear and reproducible and include example use cases. |
| **25%** | **Model Implementation**<br> - Implement the core model class for text classification. It processes datasets and returns predictions with confidence scores. |
| **20%** | **Data Loading**<br> - Develop a dataset loading feature to simplify data loading and sampling. It must handle both valid and invalid data inputs. |
| **15%** | **Evaluation**<br> - Build evaluation pipeline that tests library performance. Run tests into a CI pipeline for automatic testing on new commits. |
| **10%** | **Error Handling**<br> - Implement error handling and validation for the model and dataset components. Exceptions must be raised and handled gracefully. |
| **5%** | **Documentation**<br> - Maintain clear documentation throughout the codebase, including docstrings and inline comments. |
| **10%** | **Publicizing the Project**<br> - Share the project by posting to pypi, writing a blog post, posting to Hacker News, and sharing on r/LocalLlama. Include a project description and usage instructions in each post. |

**Comment by mikeizbicki** [comment]
Two things are not clear to me.

1.  What does "Design and conduct experiments to evaluate the model's performance" mean?  Can you be more specific? Relatedly, CI and evaluation feel like very different concepts and probably shouldn't be lumped together in the same category.

2. It's not clear to me what the entire "Dataset Management" section is for.  This seems like something that should be out of scope for this library and another library is used to load data, but I could be misunderstanding.

For publicizing: Does it make sense for this to be on pypi?

Finally, we should chat sometime about how to improve your writing.  You have a lot of spurious adjectives in your rubric and this makes your writing less credible.

**Comment by finnless** [comment]
Thanks. Revised. Probably could use one more revision.
