### ISSUE TITLE
Clarification on Supported File Formats for Summarizer

### ISSUE THREAD

**Issue by maxplush** [mikeizbicki/cmc-csci181-languages#4]
I've built my summarizer to handle HTML, PDF, and TXT files using BeautifulSoup and pdfplumber. The instructions suggest accepting any file type, but I wanted to confirm: is supporting just these three formats sufficient, or should we integrate the fulltext package to handle additional file formats?

<img width="335" alt="Screenshot 2024-08-27 at 11 16 40 AM" src="https://github.com/user-attachments/assets/924dd40b-27b8-4238-b9b3-62f24e792c77">

**Comment by mikeizbicki** [comment]
The `fulltext` library is a 1 line command to get the text from any of those formats, so it's easier (and probably a lot more robust) than the solution you've implemented.  So I'd recommend you use the `fulltext` library.

That said, I won't require it.  All of the projects in this class are meant to be things that will be useful for you, and you should do whatever will be useful for you.
