### ISSUE TITLE
Luis Gomez Project Rubric 

### ISSUE THREAD

**Issue by luisgomez214** [mikeizbicki/cmc-csci181-languages#40]
[LuisProjectProposal.pdf](https://github.com/user-attachments/files/17627549/LuisProjectProposal.pdf)

**Comment by mikeizbicki** [comment]
This looks great.

My only advise is to make sure that you show me some examples from your evaluation dataset before the due date so that I can double check for you that these are actually good examples measuring what you want to measure.

**Comment by luisgomez214** [comment]
Hello Mike, these are the questions I am planning on asking my rag system in order to evaluate it. I chose 10 "easy" questions and 10 "advanced" questions. The easy questions can be answered by text summary but the advanced ones require more complex answers beyond simple text summarization. Any question recommendations would be appreciated. 

```
[
    {
        "question": "What is the plot of Joker?",
        "expected_answer": "Joker is about Arthur Fleck, a mentally troubled man who becomes the infamous villain."
    },
    {
        "question": "Who directed the movie Joker?",
        "expected_answer": "Joker was directed by Todd Phillips."
    },
    {
        "question": "What year was Joker released?",
        "expected_answer": "Joker was released in 2019."
    },
    {
        "question": "Who played the role of Joker in the movie?",
        "expected_answer": "Joaquin Phoenix played the role of Joker."
    },
    {
        "question": "What awards did Joker win?",
        "expected_answer": "Joker won Academy Awards for Best Actor (Joaquin Phoenix) and Best Original Score."
    },
    {
        "question": "What themes does the movie Joker explore?",
        "expected_answer": "Joker explores themes of mental illness, societal neglect, and class inequality."
    },
    {
        "question": "What is the runtime of Joker?",
        "expected_answer": "The runtime of Joker is approximately 122 minutes."
    },
    {
        "question": "Where does the movie Joker take place?",
        "expected_answer": "The movie Joker takes place in Gotham City."
    },
    {
        "question": "What is Arthur Fleck's occupation in Joker?",
        "expected_answer": "Arthur Fleck is a party clown and aspiring stand-up comedian."
    },
    {
        "question": "Who composed the music for Joker?",
        "expected_answer": "Hildur Guðnadóttir composed the music for Joker."
    },
    {
        "question": "Should I take my child to watch Joker?",
        "expected_answer": "Joker is rated R for violence, disturbing content, and language. It is not suitable for children."
    },
    {
        "question": "What cultural or political messages are conveyed in Joker?",
        "expected_answer": "Joker conveys messages about inequality, mental health, societal alienation, and the neglect of marginalized individuals."
    },
    {
        "question": "How does the movie Joker depict mental illness?",
        "expected_answer": "Joker portrays mental illness through Arthur Fleck's struggles with his deteriorating mental state, societal rejection, and lack of support systems."
    },
    {
        "question": "Why is the movie Joker considered controversial?",
        "expected_answer": "Joker is controversial for its graphic depiction of violence and its exploration of societal issues that some believe could glorify vigilantism."
    },
    {
        "question": "How does Joaquin Phoenix's performance contribute to the movie's success?",
        "expected_answer": "Joaquin Phoenix's transformative and powerful portrayal of Arthur Fleck brought emotional depth to the character, earning him widespread acclaim and an Academy Award."
    },
    {
        "question": "What role does music play in Joker?",
        "expected_answer": "The haunting score by Hildur Guðnadóttir mirrors Arthur's descent into madness, while the use of popular songs contrasts with the dark themes of the movie."
    },
    {
        "question": "What inspired the story and tone of Joker?",
        "expected_answer": "Joker was inspired by character studies like Taxi Driver and The King of Comedy, which explore themes of alienation and mental instability."
    },
    {
        "question": "How does Joker differ from traditional superhero or villain movies?",
        "expected_answer": "Joker is a dark, psychological character study that focuses on Arthur Fleck's transformation into the Joker, rather than typical hero-villain conflicts."
    },
    {
        "question": "What do critics say about the cinematography in Joker?",
        "expected_answer": "Critics praise Joker's cinematography for its bleak, immersive depiction of Gotham City, capturing Arthur's isolation and descent into chaos."
    },
    {
        "question": "How does Joker address societal neglect and class inequality?",
        "expected_answer": "Joker highlights societal neglect and class inequality through Arthur's struggles with poverty, lack of mental health support, and the divide between Gotham's rich and poor."
    }
]

```

**Comment by mikeizbicki** [comment]
I see two problems:

First: How do you plan to check whether the LLM's answer is actually good?  For example, in your last question:
```
{
        "question": "How does Joker address societal neglect and class inequality?",
        "expected_answer": "Joker highlights societal neglect and class inequality through Arthur's struggles with poverty, lack of mental health support, and the divide between Gotham's rich and poor."
    }
```
What if the model instead outputs
```
Joker highlights class inequality and societal neglect through Arthur's struggles with poverty, lack of mental health support, and the divide between Gotham's rich and poor.
```
(All I did was swap the order of `class inequality and societal neglect`.)

In this case, the *semantic* meaning of the answers is the same, and so the answer should be "correct".  But how will you measure that correctness?

Second: Batman is definitely going to be in the training set of the LLM.  So the LLM is going to know the answers to all of these questions without RAG.  To evaluate the RAG component, you will need to select a movie that can't possibly be in the training set.  You could use a movie that was released after the model was released to solve this problem.

**Comment by luisgomez214** [comment]
To evaluate, I was planning on comparing the predicted response with the expected answer by using Sentence-BERT embeddings and cosine similarity. This will return a similarity expressed as a decimal that I will compare to .7 accuracy. If the similarity if below .7, then it is not semantically correct and correct if above .7. I will use the average score to determine the overall similarity of my model. 



> Second: Batman is definitely going to be in the training set of the LLM. So the LLM is going to know the answers to all of these questions without RAG. To evaluate the RAG component, you will need to select a movie that can't possibly be in the training set. You could use a movie that was released after the model was released to solve this problem.

To clarify, are you saying that instead of using the Joker (2019) movie, use a movie that is newer? If I do the movie, Wicked, that recently came out will the issue now be that it has to do with the Wizard of Oz? The training set of the LLM most likely has information about it as it is an established franchise. So, would my solution be to choose a recently released original movie to avoid this?

**Comment by mikeizbicki** [comment]
> To evaluate, I was planning on comparing the predicted response with the expected answer by using Sentence-BERT embeddings and cosine similarity. This will return a similarity expressed as a decimal that I will compare to .7 accuracy. If the similarity if below .7, then it is not semantically correct and correct if above .7. I will use the average score to determine the overall similarity of my model.

Okay, that's reasonable enough for the purposes of the class.  You should change your scoring system, however, so that you are not discretizing the cosine similarity and just add the similarities directly.  (We can talk in person if that doesn't make sense, which is fine, since it's a very vague statement.)

I wouldn't fully trust a system like this (that uses another model for evaluation) on a real world problem without some real careful analysis.    For example, the following two sentences are likely to be rated as fairly similar even though they have very different semantics for the purposes of your problem:
```
The movie Joker takes place in Gotham City.
The movie Joker takes place in Chicago.
```

> To clarify, are you saying that instead of using the Joker (2019) movie, use a movie that is newer? If I do the movie, Wicked, that recently came out will the issue now be that it has to do with the Wizard of Oz? The training set of the LLM most likely has information about it as it is an established franchise. So, would my solution be to choose a recently released original movie to avoid this?

It depends on the style of question that you ask.  I just asked Claude about Wicked, and it knew quite a bit:
```
"Wicked" is actually a stage musical, not a movie (though a film adaptation is currently in production, set to release in 2024). The musical is based on Gregory Maguire's 1995 novel "Wicked: The Life and Times of the Wicked Witch of the West."

The story serves as a prequel to "The Wizard of Oz" and follows the relationship between two witches:

    Elphaba (who becomes the Wicked Witch of the West)
    Galinda/Glinda (who becomes the Good Witch of the North)

The plot focuses on their friendship, which begins when they meet as students at Shiz University. It explores how Elphaba, despite her good intentions, becomes labeled as "wicked," while addressing themes of friendship, prejudice, political corruption, and the nature of good and evil. The story provides a different perspective on the events that lead up to Dorothy's arrival in Oz, suggesting that the traditional villain of the story may not have been so wicked after all.

The upcoming movie adaptation will star Ariana Grande as Glinda and Cynthia Erivo as Elphaba.
```
So there's still no need for RAG to get any of that information about wicked.  But if you ask something like: Did critics have a good or bad review of the movie Wicked?  Then that is something that won't be in the training set and you'd need RAG for.
