### ISSUE TITLE
Alex Nasoni Project Rubric

### ISSUE THREAD

**Issue by alexcnsf** [mikeizbicki/cmc-csci181-languages#41]
[AN Final Project Rubric.pdf](https://github.com/user-attachments/files/17628812/AN.Final.Project.Rubric.pdf)

**Comment by mikeizbicki** [comment]
Goals T1-T2 are acceptable, but you might want to revisit them in light of the notes below.

Goal T3 can't count for credit in this course.  Also, there are already many high quality flashcard apps (and you are unlikely to be able to improve on them).  Anki is the most popular, but web-based ones like memrise are also popular.  You should have your system output in a format that is compatible with one of these other applications and use that application.

For evaluation:
- Bullet point 1 is unclear to me.  How exactly will you measure the quality?  It will be tricky to come up with some sort of programmatic measure of flashcard quality, but you'll have to do that.  
- Bullet point 2 doesn't make sense without the app development component, so you'll have to remove that.
- Bullet point 3 is a great goal.  I hope it works out :)

**Comment by alexcnsf** [comment]
Here is my revised rubric: [AN Final Project Rubric 2.0.pdf](https://github.com/user-attachments/files/17726567/AN.Final.Project.Rubric.2.0.pdf)
Let me know what you think!

**Comment by alexcnsf** [comment]
Alex Nasoni  
CSCI 181: Special Topics for CS
Professor Izbicki  

## Final Project Grading Rubric  

| **Grade Percentage** | **Task**                                  | **Description**                                                                                                                                                                                                                                                         |
|-----------------------|-------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **20%**              | **T1: Document Input and Chunking**       | - Prompt users to input file paths of their pdf of textbooks. <br> - Split the document up by Chapters, then Definitions and Lemmas, and then examples until chunks under the appropriate chunk size limits. <br> - Add other guard rails to prevent bad chunks.           |
| **25%**              | **T2: Accurate Figure Extraction**        | - Create an algorithm to accurately extract the images of important figures to be used on flashcards. <br> - Make sure these images include the full figure, but not other text. <br> - Also collect other relevant information such as captions or examples about the figure that could be used to help compile accurate flashcards for the figures. |
| **35%**              | **T3: Content Flashcard Creator**         | - For each chunk, use prompts to Groq to extract key terms, definitions, and summarizations of the text to be used for all flashcards. <br> - Additionally use the collected snapshots of figures and their surrounding text to create. <br> - Store all flashcards in a comma-separated plain text file that is compatible with the popular Anki flashcard software and includes: <br> - Front: Key concept or question. <br> - Back: Answer or explanation. <br> - Tags (optional): categories to sort topics by their chapter, subsections, topic, or maybe even page numbers. <br> - Additionally, it is important that this is compatible with the snapshots of the figures from the text so those can be displayed on the front or back of the flashcard. |
| **30%**              | **Evaluation (Breadth, Quality, and Visual Accuracy)** | - I want to evaluate the flashcard breadth by gathering standard flashcard topics from the relevant chapters of my Probability textbook I would expect to be covered and compare them to the topics my generated flashcard deck includes. <br> - Next I want to evaluate the quality of the flashcard by going through and judging if each flashcard is actually correct. <br> - Lastly I want to evaluate the accuracy of extracting the figures from the textbook by judging what percent of them are captured accurately without cutting off the figures or including other text. |
