### ISSUE TITLE
CLI Chatbot Final Project - Ainslee & Rowan

### ISSUE THREAD

**Issue by ains-arch** [mikeizbicki/cmc-csci181-languages#43]
# Proposal
 
Our project is to design a chatbot that can interact with the user's command line and help with system administration.

1. In which we pipe an LLM into /bin/bash and see what happens
1. @ains-arch and @RowanGray472 at [repo](https://github.com/RowanGray472/command-line-chatbot)
1. Outline
    1. LLaMa model or Groq
    1. RAG system with manpages (either something we download from somewhere or something that can query the ones that are already on the computer)
    1. Something that can be queried from the command line for text interface
    1. Can input to the command line and receive the outputs of the commands run in order to take further action
1. Sources/inspiration
[initial X thread](https://x.com/bshlgrs/status/1840577720465645960)
[log](https://gist.github.com/bshlgrs/57323269dce828545a7edeafd9afa7e8)
[demo](https://www.dropbox.com/scl/fi/a3ellhrgmbn9r8ximrbcd/buck-scaffold-demo.mov?rlkey=4cb2ws4xtlpezlh0q7sxa9gcy&e=2&st=fdxpp422&dl=0)
[news coverage](https://www.theregister.com/2024/10/02/ai_agent_trashes_pc/)

# Rubric

|     | Backend (50%)                                               |
|-----|-------------------------------------------------------------|
| 15% | Functional RAG system                                       |
|  5% | Good/fast SQL database of manpages                          |
| 10% | Summary/keyword/prompt engineering                          |
|  5% | RAG system results                                          |
|  5% | Command line utility that can recieve outputs               |
|  5% | Rights management with read-only normal mode                |
|  5% | Rights management with 'freestyle mode' for read-write mode |

|     | Frontend (25%)                                                            |
|-----|---------------------------------------------------------------------------|
| 15% | It actually works (in a development environment/VM on our machine)        |
|  5% | It actually works (in a production environment/bare metal on our machine) |
|  5% | It actually works (well)                                                  |
     
|    | Vibes (10%)                                                    |
|----|----------------------------------------------------------------|
| 5% | Engineering: Code/design quality                               |
| 5% | Communications: README professionalism & sysadmin Reddit posts |

|     | Research Project (15%)                                               |
|-----|----------------------------------------------------------------------|
|  5% | ~20 concrete tasks with associated output/action to evaluate success |
| 10% | accuracy on read-only tasks                                          |
|  5% | accuracy on read/write tasks                                         |
    
|     | Extra Credit Opportunities (60%)                             |
|-----|--------------------------------------------------------------|
|  5% | It's on time and under budget                                |
|  5% | It all runs locally                                          |
|  5% | It takes voice input via Whisper                             |
| 10% | It takes voice input via Whisper that is good (uses grammar) |
| 15% | We fine tune our model                                       |
| 10% | Our social media posts actually get attention                |
|  5% | 'Freestyle mode' is funny                                    |
|  5% | We convince you to run any of it on your machine             |

**Comment by mikeizbicki** [comment]
We clarified in person what "Well-implemented database", "Integration with bash" and "Experimental component" mean, but you should clarify them here in writing so I don't forget.

Also, remove the presentation 5% and put it in the experimental component portion.

**Comment by ains-arch** [comment]
Updates made.

**Comment by mikeizbicki** [comment]
Looks good :)
