### ISSUE TITLE
Fun Chess/LLM/Grammar link

### ISSUE THREAD

**Issue by mikeizbicki** [mikeizbicki/cmc-csci181-languages#48]
[This website](https://dynomight.net/chess/) shows how recent LLMs have lost some chess playing ability.  There's two tie-ins to class:

1. He uses llama.cpp and grammars to enforce that models make legal moves.  (This is slightly different than what we did for whisper.cpp, since our grammar only enforced correct syntax and not actually accounting for the details of chess rules.)  Note also how he complains about OpenAI models not supporting any form of grammar constraints.
2. This is the style you should be aiming for in your final projects.  If you write something like this, you'll definitely get an A.

**Comment by finnless** [comment]
Hacker News Discussions for this article:
 - https://news.ycombinator.com/item?id=42138289
 - https://news.ycombinator.com/item?id=42138276

Is this saying instruction tuning makes these LLM's worse or that some other thing is making them worse? I wonder if an old version of GPT-3 or GPT-4 would do well. `davinci-002` and `gpt-4-0314` (the original GPT-4) are both still available.

**Comment by mikeizbicki** [comment]
It's not clear to me exactly what the problem is.  It's suggestive that instruction tuning is the problem, but it could be something else.
