### ISSUE TITLE
Clarification on Setting Up tests for RAG Testing

### ISSUE THREAD

**Issue by maxplush** [mikeizbicki/cmc-csci181-languages#55]
## Summary

I am trying to set up a `tests.py` Python script to automate tests for evaluating the accuracy of my RAG system, but I wanted to check whether I am missing any steps or redundancy in the process.

## Test Flow

The tests loop through questions stored in a CSV file, and contains an "answer key" with five keywords for each question.

1. **Test Questions:**
   - For each question in the CSV file, send the question to the RAG system.
   - Check if the provided answer contains at least 3 out of the 5 "answer key words" listed for that question in the CSV file.
   - If the answer matches the criteria, assign a score of 1 (correct), otherwise, assign a score of 0 (incorrect).

2. **Accuracy Calculation:**
   - Calculate the overall accuracy by dividing the total number of correct answers by the total number of questions.

3. **Malicious Question Detection:**
   - Before sending the questions to the RAG system, pass each question through a malicious question detector LLM (using the same logic as in my main code).

## Issue

Not sure if this is an issue but in order to complete these tests the database needs to be set up beforehand since I am using FTS5 (Full Text Search) for question matching. This requires creating and pre-loading a database before proceeding with the tests.

I'd imagine someone would want to test the quality of the LLM BEFORE running the main code. So there would need to be another separate database created. 

## Question

1. Are there any parts of my testing process that might be redundant?

**Comment by mikeizbicki** [comment]
Your test flow is all reasonable.  (I would personally consider a 3/5 to be a 0.6 rather than a 1.0, and a 5/5 to be needed to be a 1.0, but either way will provide some measure of confidence in your model's ability.)

> Not sure if this is an issue but in order to complete these tests the database needs to be set up beforehand since I am using FTS5 (Full Text Search) for question matching. This requires creating and pre-loading a database before proceeding with the tests.

This is fine.  Just ensure that the README provides the proper setup instructions.

**Comment by maxplush** [comment]
Got it thank you for clearing this up. I'll add this to the README.

**Comment by maxplush** [comment]
One other question. Since 5 keywords seems to be sometimes limiting the LLM could spit out "life guard" instead of "lifeguard". Is having more than 5 listed be a smart idea?

Also for the malicious content it only returns two words. Content warning and the number related to the malicious offense
