### ISSUE TITLE
Terminal Setup

### ISSUE THREAD

**Issue by danzhechen** [mikeizbicki/cmc-csci181-languages#8]
I am using my terminal on macbook and I wonder how to set up my terminal in colorful settings like yours @mikeizbicki. I did a few research online but most of them requires external installation. I remembered you briefly mentioned that in Big Data, but I could not find it. Thank you for your help in advance.

**Comment by ains-arch** [comment]
The default shell on macOS is zsh, not bash. you could look into editing `.zshrc` to add color; I'm not sure how much would be supported without additional installs.

Or, you can [change your default shell](https://support.apple.com/guide/terminal/change-the-default-shell-trml113/mac) to bash and then use Mike's `.bashrc` from his [dotfiles](https://github.com/mikeizbicki/dotfiles/tree/master).
```
$ curl https://raw.githubusercontent.com/mikeizbicki/dotfiles/master/.bashrc > ~/.bashrc
```

More info on his configuration can be found in [the Data Structures assignment](https://github.com/mikeizbicki/cmc-csci046/blob/2023spring/topic_00_unix/lambda-server.md).

Or, if you want, you can [try using my dotfiles](https://github.com/ains-arch/dotfiles), though I make no promises they will work as smoothly.

**Comment by RowanGray472** [comment]
Idk if I'm missing something but when you make a new terminal you can pick from a bunch of themes there


<img width="621" alt="Screenshot 2024-09-05 at 11 08 51 AM" src="https://github.com/user-attachments/assets/4cc60c5c-118a-4de7-ab57-4774edca5526">

Or you can go into settings in the terminal application and make your own custom theme there!

<img width="722" alt="Screenshot 2024-09-05 at 11 10 40 AM" src="https://github.com/user-attachments/assets/4b8adbc6-192b-40c7-8766-15b954fd49b9">
